extends RefCounted
class_name NPCRoster


static func build(seed: int) -> Array[NPCProfile]:
	var pool: Array[NPCProfile] = [
		NPCProfile.new({
			"id": "calm_regular",
			"display_name": "지민",
			"trait_label": "차분한 단골",
			"action_speed": 1.00,
			"patience": 1.25,
			"request_bias": 0.65,
			"tip_multiplier": 1.00,
			"aggression": 0.95,
			"warning_line": "천천히 하셔도 돼요.",
			"miss_line": "아, 요청은 다음에 해도 돼요.",
			"dialogue": {
				"call": ["콜.", "받을게요."],
				"raise": ["레이즈.", "조금 올릴게요."],
				"fold": ["폴드.", "전 빠질게요."],
				"all_in": ["올인.", "여기까지 갈게요."],
				"all_in_react": ["오.", "크게 가네요."],
				"request": ["딜러, 칩 좀 부탁할게요.", "칩 교환 부탁드려요."],
				"fast": ["깔끔하네요.", "진행 좋네요."],
				"request_done": ["감사해요.", "됐어요."],
				"win": ["좋네요.", "고마워요."],
				"delay": ["괜찮아요, 천천히."],
			},
		}),
		NPCProfile.new({
			"id": "impatient_reg",
			"display_name": "맥스",
			"trait_label": "성급한 레귤러",
			"action_speed": 0.72,
			"patience": 0.62,
			"request_bias": 0.85,
			"tip_multiplier": 1.10,
			"aggression": 1.15,
			"warning_line": "딜러, 진행 좀요.",
			"miss_line": "이 테이블 왜 이렇게 느려요?",
			"dialogue": {
				"call": ["콜.", "빨리 가죠."],
				"raise": ["레이즈.", "올립니다."],
				"fold": ["폴드.", "다음."],
				"all_in": ["올인.", "갑시다."],
				"all_in_react": ["오, 세게 가네.", "좋아, 보자고."],
				"request": ["딜러, 칩 좀 바꿔줘요.", "칩 교환이요."],
				"fast": ["이 정도 속도 좋죠.", "좋네, 바로바로."],
				"request_done": ["오케이.", "됐습니다."],
				"win": ["좋았어.", "그렇지."],
				"delay": ["딜러, 진행 좀요.", "아직 멀었어요?"],
			},
		}),
		NPCProfile.new({
			"id": "new_player",
			"display_name": "소연",
			"trait_label": "초보 플레이어",
			"action_speed": 1.28,
			"patience": 1.05,
			"request_bias": 1.35,
			"tip_multiplier": 0.95,
			"aggression": 0.85,
			"warning_line": "저... 이거 맞게 된 거죠?",
			"miss_line": "저 아직 잘 모르겠어요.",
			"dialogue": {
				"call": ["저 콜이요.", "콜... 맞죠?"],
				"raise": ["저 레이즈 할게요.", "이렇게 올리면 되죠?"],
				"fold": ["아, 폴드할게요.", "저는 빠질게요."],
				"all_in": ["저... 올인이요.", "그냥 다 넣을게요."],
				"all_in_react": ["헉, 올인이에요?", "와, 갑자기요?"],
				"request": ["저... 칩 좀 바꿔주실래요?", "이 칩 교환해도 돼요?"],
				"fast": ["와, 빠르다.", "딜 되게 빠르네요."],
				"request_done": ["아 감사합니다.", "네, 됐어요!"],
				"win": ["제가 이긴 거예요?", "진짜요?"],
				"delay": ["저 지금 기다리면 되는 거죠?"],
			},
		}),
		NPCProfile.new({
			"id": "chatty_regular",
			"display_name": "토니",
			"trait_label": "말 많은 단골",
			"action_speed": 0.92,
			"patience": 0.82,
			"request_bias": 1.55,
			"tip_multiplier": 1.08,
			"aggression": 1.10,
			"warning_line": "딜러~ 내 거 잊은 거 아니죠?",
			"miss_line": "아까부터 말했는데~",
			"dialogue": {
				"call": ["콜~", "일단 봅시다."],
				"raise": ["레이즈 갑니다.", "자, 좀 올려볼까."],
				"fold": ["아 이건 아니네, 폴드.", "됐어, 다음 판."],
				"all_in": ["자~ 올인!", "여기서 다 갑니다."],
				"all_in_react": ["오호, 분위기 뜨거운데?", "야, 이거 재밌네."],
				"request": ["딜러~ 칩 좀 부탁해요.", "여기 칩 교환 좀~"],
				"fast": ["딜러 손 빠르네~", "오, 오늘 컨디션 좋은데?"],
				"request_done": ["땡큐 딜러~", "역시 빠르네."],
				"win": ["이 맛이지~", "자, 다음 판 가자고."],
				"delay": ["딜러~ 우리 잊은 거 아니죠?", "자자, 갑시다~"],
			},
		}),
		NPCProfile.new({
			"id": "demanding_vip",
			"display_name": "김사장",
			"trait_label": "까다로운 VIP",
			"action_speed": 0.78,
			"patience": 0.55,
			"request_bias": 1.30,
			"tip_multiplier": 1.45,
			"aggression": 1.20,
			"warning_line": "딜러, 바로 처리해 주세요.",
			"miss_line": "서비스가 이래서야 되겠어요?",
			"dialogue": {
				"call": ["콜.", "받죠."],
				"raise": ["레이즈.", "올려요."],
				"fold": ["폴드.", "버립니다."],
				"all_in": ["올인.", "정리합시다."],
				"all_in_react": ["과감하군.", "보죠."],
				"request": ["딜러, 칩 교환해 주세요.", "이 칩 정리 좀 해주세요."],
				"fast": ["좋습니다.", "이 정도면 됐어요."],
				"request_done": ["됐습니다.", "좋아요."],
				"win": ["좋군.", "정산해 주세요."],
				"delay": ["딜러, 지금 뭐 하는 겁니까?", "바로 진행하세요."],
			},
		}),
		NPCProfile.new({
			"id": "relaxed_tourist",
			"display_name": "찰리",
			"trait_label": "느긋한 관광객",
			"action_speed": 1.38,
			"patience": 1.48,
			"request_bias": 0.50,
			"tip_multiplier": 1.00,
			"aggression": 0.90,
			"warning_line": "No rush, dealer.",
			"miss_line": "It's okay. Next time.",
			"dialogue": {
				"call": ["Call.", "I'm in."],
				"raise": ["Raise.", "Let's make it bigger."],
				"fold": ["Fold.", "Next one."],
				"all_in": ["All in.", "Why not?"],
				"all_in_react": ["Whoa.", "Big one."],
				"request": ["Dealer, change please.", "Can I get change?"],
				"fast": ["Nice dealing.", "Smooth."],
				"request_done": ["Thanks.", "Perfect."],
				"win": ["Nice.", "Good hand."],
				"delay": ["No rush.", "Take your time."],
			},
		}),
	]

	var rng := RandomNumberGenerator.new()
	rng.seed = seed
	for i in range(pool.size() - 1, 0, -1):
		var j: int = rng.randi_range(0, i)
		var temp: NPCProfile = pool[i]
		pool[i] = pool[j]
		pool[j] = temp

	return pool
